---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: chuck-says-api-query
  name: chuck-says-api-query-lb
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 48080
      protocol: TCP
      targetPort: 48080
  selector:
    app: chuck-says-api-query
status:
  loadBalancer: {}